version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.4

    steps:
      - checkout

      - run:
          name: Push code to repo
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
      
      - deploy:
          name: Trigger github push
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "kernlee23@gmail.com"
            git config user.name "kernleee"
            git add .
            git commit -m "Update via CircleCI [ci skip]"
            # Push quietly to prevent showing the token in log
            git push -u origin master
