version: 2
jobs:
  build:
    macos:
      xcode: 10.2.1

    steps:
      - checkout

      - run:
          name: Update brew
          command: source ~/project/scripts/brew_update.sh

      - run:
          name: Test new release formula
          command: source ~/project/scripts/test_release_formula.sh

      - run:
          name: Integration test
          command: source ~/project/scripts/test_integ_formula.sh

      - run:
          name: Make changes to GitHub clone
          command: source ~/project/scripts/upgrade_formula.sh

      - add_ssh_keys:
          fingerprints:
            - "0e:4f:57:99:17:76:54:51:18:08:4c:a3:0f:bc:28:84"
      
      - deploy:
          name: Trigger GitHub release
          command: source ~/project/scripts/push_to_github.sh
